#include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/**.g.dart
    - test/**/**.mocks.dart

linter:
  rules:
    # ------ Disabled individual rules ----- #
    always_put_required_named_parameters_first: false
    annotate_overrides: false
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false
    depend_on_referenced_packages: false
    no_leading_underscores_for_local_identifiers: false
    prefer_double_quotes: false
    public_member_api_docs: false
    sort_constructors_first: false


    # ------ Enabled individual rules ------ #
    always_specify_types: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    avoid_escaping_inner_quotes: true
    avoid_print: false
    avoid_slow_async_io: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    empty_statements: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unnecessary_overrides: true
    unnecessary_statements: true

    # prefer_const_constructors: true
    # prefer_const_declarations: true
    # prefer_const_literals_to_create_immutables: true
    # prefer_final_fields: true
    # prefer_final_locals: true
    # require_trailing_commas: true
    # unnecessary_await_in_return: true
    # unnecessary_breaks: true
    # unnecessary_final: true
    # unnecessary_lambdas: true
    # unnecessary_late: true
    # unnecessary_null_checks: true
    # unnecessary_parenthesis: true
    # unnecessary_raw_strings: true
